# Generated by Django 2.2.4 on 2019-08-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakedata',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
