# Generated by Django 2.2.4 on 2019-08-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakeapp', '0002_auto_20190817_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakedata',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fakedata',
            name='job',
            field=models.CharField(max_length=100),
        ),
    ]
